### ISSUE TITLE
Ack I can't find everybody's email address!

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/BikeSafety#26]
Hi @BikeSafety/owners,

I hope this gets to you all - _just_ in case @e2charlie @saeed3068 @docmarionum1 ^^^

As I mentioned at the last meetup I'm not a-gonna make it to tomorrow's meeting so here's my checkin/progress:
- I finished #14, #15, and #16 -- or at least, they're better than they were!
- I've added some more notes to #17 and #18 -- those should be pretty easy for anyone with even a little javascript experience to pick up.
- I've grabbed #4 and #5 - if you want to work on one of  them tho feel free to steal them from me.

---

It looks like we are _almost_ half way done with the user contributed feature - if something grabs your interest feel free to grab something: https://github.com/BikeSafety/BikeSafety/milestones

**Comment by docmarionum1** [comment]
Is there actually a meetup tomorrow?  Didn't see anything listed on the CFD meetup page.

**Comment by dsummersl** [comment]
Ack you're right its the 12th - looks like its gonna be at Caktus Group too.

**Comment by dsummersl** [comment]
Hey hey hey @BikeSafety/owners,

Still don't have everybody's emails so I'm baa-ack.

Adam sent me a promo code for free tickets to Saturday's DataJam. I'm gonna go, probably just work on the Bike app and eat free food. If you all can come lemme know and I'll forward you the code to get a free ticket. My email: DSUMMERSL at you know where: gmail.

**Comment by docmarionum1** [comment]
Won't be able to make it.  I'll be on my way to Rome that day.  Have fun!

**Comment by dsummersl** [comment]
US have fun!? Sounds like your the one doing that. Have a good trip!
