### ISSUE TITLE
Remove the 'layers' icon from the upper-right part of the map

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/BikeSafety#29]
I dunno if this is possible, but it'd be nice. The angular leaflet plugin we use probably has an option to do this.

**Comment by flowersw** [comment]
I think it is possible (to  at least move the icon), and I found the docs and a couple of links which were helpful. But, I couldn't figure out how to change the settings in the CSS file. See what you think.

http://gis.stackexchange.com/questions/41768/leaflet-how-to-move-the-layer-control-menu
http://leafletjs.com/reference.html#control-positions

**Comment by dsummersl** [comment]
This is the code:

```
            $('.leaflet-control-layers-toggle').hide()
```

Ande this is where it should go:

https://github.com/BikeSafety/BikeSafety/blob/master/html/includes/angular/MainMap.js#L123
