### ISSUE TITLE
Simplify frontend file structure.

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/BikeSafety#32]
Suggested structure, maybe this: https://scotch.io/tutorials/angularjs-best-practices-directory-structure

This will involve moving angular files and their refs around. Mainly this is just in layout.jade (where all frontend angular files come from). If the jade files are moved (I think they should be)...then edit GUI.js so that it still compiles it all to html.

**Comment by docmarionum1** [comment]
I might take a crack at this.  It would make me feel so good to clean this up.
