### ISSUE TITLE
Bicyclist Injury data needs to be normalized

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/BikeSafety#38]
It looks like this:

O: No Injury
A: Disabling Injury
B: Evident Injury
C: Possible Injury
K: Killed
Evident Injury
Possible Injury
Disabling Injury
No Injury
Other Injury
Killed

And it would be better if it looked like:

No Injury
Possible Injury
Evident Injury
Disabling Injury
Killed
Other Injury
Unknown

**Comment by flowersw** [comment]
I have it looking better. Two options are still giving me trouble: driver/biker injury. They are still pulling options from their original data I believe. If someone gets a chance, take a look. Is there any chance by configuring these differently the data streaming in will not know where to go?
