### ISSUE TITLE
Jump to the map after adding a new accident.

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/BikeSafety#5]
The 'user contributed' dataset will also need to be updated to show the new accident.

**Comment by dsummersl** [comment]
Jumping is the easy part, just add `$location.path("/");`
to https://github.com/BikeSafety/BikeSafety/blob/master/html/includes/angular/AddAccident.js#L138

I'm not sure how to refresh the data so that the new accident is on the map. Ideally the map would focus/center on the new accident.

**Comment by docmarionum1** [comment]
@dsummersl can you commit the change you made to just go to the map without the pan and zoom?  Or was that just location.path("/")?

**Comment by dsummersl** [comment]
I pushed the branch here: https://github.com/BikeSafety/BikeSafety/tree/jump_to_map

**Comment by docmarionum1** [comment]
Ah, I started on this a bit before you took it back.  I hope you didn't start working on it yet @dsummersl !

Basically what I found was that there was a conflict between how we were doing our own scaling and the scaling in the d3svgoverlay library.  When we did the zoom what was happening WASNT that the features were being removed, they were actually just being made very tiny.  (Too tiny to be visible).  What I did was make our scaling match the scaling in that library, which is double every zoom in.  This leads to very large features when all the way zoomed in.  Which isn't great. But I couldn't see a way to configure the d3svgoverlay library with a custom zoom function.

@dsummersl  Can you take a look at this and double check that it works?

**Comment by dsummersl** [comment]
Sweet - nope I didn't get the chance! hah, very tiny icons! I'll take a look at it and get back to you.

**Comment by dsummersl** [comment]
Awesome - sorry it took me so long to get to this. Just tried it out and it works! Dots are a little smaller - I'll take a quick look at that before I merge it in to master.
